### ISSUE TITLE
is there a limitation for the lines ?

### ISSUE THREAD

**Issue by mohelbahy** [fireeye/GeoLogonalyzer#7]
hello guys 
I tried the script with CSV log file contains 14606 lines 
I got the following error
Traceback (most recent call last):
  File "./GeoLogonalyzer.py", line 980, in <module>
    main(args)
  File "./GeoLogonalyzer.py", line 662, in main
    time, ip_string, user, hostname, client = get_csv_details(line)
  File "./GeoLogonalyzer.py", line 301, in get_csv_details
    ip_string = line_list[2].strip()

are you aware about any limitation ?

**Comment by davidpany** [comment]
There is no known input file size limit. I recently tested on a CSV file with 63,206 rows of input. Is there more to your error? The traceback you shared looks incomplete and does not seem to indicate why the tool failed.
